bbox:
  middle: [50.7320436, 7.0967647]
  xLength: 0.019
  xyRatio: 1

# Düsseldorf: [51.2197340, 6.7943015]
# Dortmund: [51.5178935, 7.4592831]
# Rhade: [51.7509458, 6.9483979]
# Essen: [51.4514769, 7.0144679]
# Köln: [50.9427839, 6.9590705]
# Wuppertal: [51.2545808, 7.1500551]
# Hamm: [51.6785747, 7.8077130]
# Münster: [51.9564055, 7.6357920]
# Bonn: [50.7320436, 7.0967647]



# the heightMult value scales the image at the y-axis. This has to be done to so the conversion from latitude and longitude to x and y works. There should be a way that this works better
heightMult: 1.61

# readme workflow to download .osm.pbm, select area on osm with export or get middle form url

svgWidth: 1000
background-color: "#ffffff"


requests:
  - table: "osm_highway_linestring"
    restrictions: ""
    stroke-width: 1
    stroke: "#000000"
    fill: "none"

  - table: "osm_railway_linestring"
    restrictions: ""
    stroke-width: 1
    stroke: "#000000"
    fill: "none"